package com.tzcpa.mapper.student;

import com.tzcpa.model.student.TeamMonthlyProfitStatementDO;
import io.swagger.models.auth.In;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface TeamMonthlyProfitStatementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_monthly_profit_statement
     *
     * @mbggenerated
     */
    int insert(TeamMonthlyProfitStatementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_monthly_profit_statement
     *
     * @mbggenerated
     */
    int insertSelective(TeamMonthlyProfitStatementDO record);

    int insertBanchMonthlyProfitStatement(@Param("teamMonthlyProfitStatementDOs") List<TeamMonthlyProfitStatementDO> teamMonthlyProfitStatementDOs);

    List<TeamMonthlyProfitStatementDO> selectFromIntermediate(@Param("classId") Integer classId , @Param("teamId") Integer teamId ,
                                                              @Param("year") Integer year,@Param("month") Integer month,
                                                              @Param("nextYear") Long nextYear,@Param("nextMonth") Long nextMonth);

  Map<String,Double> getHalfYearData(@Param("classId") Integer classId , @Param("teamId") Integer teamId , @Param("year") Integer year);

    /**
     * @author:     wangzhangju
     * @date:       2019/5/29 11:42
     * @param:      null
     * @return:
     * @exception:
     * @description: 查询月度利润表格
     * @step:
     */
    List<TeamMonthlyProfitStatementDO> getMonthlyForm(@Param("classId") Integer classId , @Param("teamId") Integer teamId ,
                                                      @Param("year")Integer year, @Param("currentMonth") Date currentMonth);


}