package com.tzcpa.mapper.student;

import com.tzcpa.model.student.TeamAnnualWorthGather;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface TeamAnnualWorthGatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_annual_worth_gather
     *
     * @mbggenerated
     */
    int insert(TeamAnnualWorthGather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_annual_worth_gather
     *
     * @mbggenerated
     */
    int insertSelective(TeamAnnualWorthGather record);

    /**
     *  年末获取年度分析表数据
     * @return
     */
    List<TeamAnnualWorthGather> getAnnual(@Param("classId") Integer classId,@Param("teamId") Integer teamId,
                                          @Param("lastYear") Integer lastYear,@Param("currentDate") Date currentDate);

    /**
     * @author:     wangzhangju
     * @date:       2019/6/3 14:48
     * @param:      null
     * @return:
     * @exception:
     * @description: 查询年度分析报表数据
     * @step:
     */
    TeamAnnualWorthGather getTeamAnnualWorthGather(@Param("classId") Integer classId,@Param("teamId") Integer teamId,
                                                   @Param("year") Integer year);
    
    Double getYFFZB(@Param("classId") Integer classId,@Param("teamId") Integer teamId,
            @Param("year") Integer year);
}