package com.tzcpa.mapper.treatment;

import com.tzcpa.model.treatment.TeamIntermediateVariableDO;

public interface TeamIntermediateVariableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_intermediate_variable
     *
     * @mbggenerated
     */
    int insert(TeamIntermediateVariableDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_intermediate_variable
     *
     * @mbggenerated
     */
    int insertSelective(TeamIntermediateVariableDO record);
}