package com.tzcpa.model.student;

import java.io.Serializable;
import java.math.BigDecimal;

public class TeamAnnualWorthGather implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.net_assets_income_rate
     *
     * @mbggenerated
     */
    private BigDecimal netAssetsIncomeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.retained_profits
     *
     * @mbggenerated
     */
    private String retainedProfits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.operation_revenue
     *
     * @mbggenerated
     */
    private String operationRevenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.net_asset_value_per_share
     *
     * @mbggenerated
     */
    private String netAssetValuePerShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.earnings_per_share
     *
     * @mbggenerated
     */
    private String earningsPerShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.sales_margin
     *
     * @mbggenerated
     */
    private String salesMargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.gross_margin
     *
     * @mbggenerated
     */
    private String grossMargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.net_profit_margin_on_sales
     *
     * @mbggenerated
     */
    private String netProfitMarginOnSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.operating_profit_ratio
     *
     * @mbggenerated
     */
    private String operatingProfitRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.year_over_year_growth_in_earnings_per_share
     *
     * @mbggenerated
     */
    private String yearOverYearGrowthInEarningsPerShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.year_over_year_growth_rate_of_operating_income
     *
     * @mbggenerated
     */
    private String yearOverYearGrowthRateOfOperatingIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.year_on_year_growth_rate_of_net_profit
     *
     * @mbggenerated
     */
    private String yearOnYearGrowthRateOfNetProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.year_over_year_return_on_equity_growth
     *
     * @mbggenerated
     */
    private String yearOverYearReturnOnEquityGrowth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.rate_of_stock_turnover
     *
     * @mbggenerated
     */
    private String rateOfStockTurnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.turnover_of_total_capital
     *
     * @mbggenerated
     */
    private String turnoverOfTotalCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.total_assets
     *
     * @mbggenerated
     */
    private String totalAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.net_asset
     *
     * @mbggenerated
     */
    private String netAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.asset_liability_ratio
     *
     * @mbggenerated
     */
    private String assetLiabilityRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.liquidity_ratio
     *
     * @mbggenerated
     */
    private String liquidityRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.quick_ratio
     *
     * @mbggenerated
     */
    private String quickRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.sales_growth_rate
     *
     * @mbggenerated
     */
    private String salesGrowthRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_operating_income_limousine
     *
     * @mbggenerated
     */
    private String compositionOfOperatingIncomeLimousine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_operating_income_h6
     *
     * @mbggenerated
     */
    private String compositionOfOperatingIncomeH6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_operating_income_pickup
     *
     * @mbggenerated
     */
    private String compositionOfOperatingIncomePickup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_operating_income_wey
     *
     * @mbggenerated
     */
    private String compositionOfOperatingIncomeWey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_operating_income_h8
     *
     * @mbggenerated
     */
    private String compositionOfOperatingIncomeH8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_net_profit_limousine
     *
     * @mbggenerated
     */
    private String compositionOfNetProfitLimousine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_net_profit_h6
     *
     * @mbggenerated
     */
    private String compositionOfNetProfitH6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_net_profit_pickup
     *
     * @mbggenerated
     */
    private String compositionOfNetProfitPickup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_net_profit_wey
     *
     * @mbggenerated
     */
    private String compositionOfNetProfitWey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.composition_of_net_profit_h8
     *
     * @mbggenerated
     */
    private String compositionOfNetProfitH8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.development_expenditure
     *
     * @mbggenerated
     */
    private String developmentExpenditure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.development_expenditure_percentage_revenue
     *
     * @mbggenerated
     */
    private String developmentExpenditurePercentageRevenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.h6_market_share
     *
     * @mbggenerated
     */
    private String h6MarketShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.h8_market_share
     *
     * @mbggenerated
     */
    private String h8MarketShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.wey_market_share
     *
     * @mbggenerated
     */
    private String weyMarketShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.new_product_contribution_rate
     *
     * @mbggenerated
     */
    private String newProductContributionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.class_id
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_annual_worth_gather.team_id
     *
     * @mbggenerated
     */
    private Integer teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_team_annual_worth_gather
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.id
     *
     * @return the value of t_team_annual_worth_gather.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.id
     *
     * @param id the value for t_team_annual_worth_gather.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.year
     *
     * @return the value of t_team_annual_worth_gather.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.year
     *
     * @param year the value for t_team_annual_worth_gather.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.net_assets_income_rate
     *
     * @return the value of t_team_annual_worth_gather.net_assets_income_rate
     *
     * @mbggenerated
     */
    public BigDecimal getNetAssetsIncomeRate() {
        return netAssetsIncomeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.net_assets_income_rate
     *
     * @param netAssetsIncomeRate the value for t_team_annual_worth_gather.net_assets_income_rate
     *
     * @mbggenerated
     */
    public void setNetAssetsIncomeRate(BigDecimal netAssetsIncomeRate) {
        this.netAssetsIncomeRate = netAssetsIncomeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.retained_profits
     *
     * @return the value of t_team_annual_worth_gather.retained_profits
     *
     * @mbggenerated
     */
    public String getRetainedProfits() {
        return retainedProfits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.retained_profits
     *
     * @param retainedProfits the value for t_team_annual_worth_gather.retained_profits
     *
     * @mbggenerated
     */
    public void setRetainedProfits(String retainedProfits) {
        this.retainedProfits = retainedProfits == null ? null : retainedProfits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.operation_revenue
     *
     * @return the value of t_team_annual_worth_gather.operation_revenue
     *
     * @mbggenerated
     */
    public String getOperationRevenue() {
        return operationRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.operation_revenue
     *
     * @param operationRevenue the value for t_team_annual_worth_gather.operation_revenue
     *
     * @mbggenerated
     */
    public void setOperationRevenue(String operationRevenue) {
        this.operationRevenue = operationRevenue == null ? null : operationRevenue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.net_asset_value_per_share
     *
     * @return the value of t_team_annual_worth_gather.net_asset_value_per_share
     *
     * @mbggenerated
     */
    public String getNetAssetValuePerShare() {
        return netAssetValuePerShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.net_asset_value_per_share
     *
     * @param netAssetValuePerShare the value for t_team_annual_worth_gather.net_asset_value_per_share
     *
     * @mbggenerated
     */
    public void setNetAssetValuePerShare(String netAssetValuePerShare) {
        this.netAssetValuePerShare = netAssetValuePerShare == null ? null : netAssetValuePerShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.earnings_per_share
     *
     * @return the value of t_team_annual_worth_gather.earnings_per_share
     *
     * @mbggenerated
     */
    public String getEarningsPerShare() {
        return earningsPerShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.earnings_per_share
     *
     * @param earningsPerShare the value for t_team_annual_worth_gather.earnings_per_share
     *
     * @mbggenerated
     */
    public void setEarningsPerShare(String earningsPerShare) {
        this.earningsPerShare = earningsPerShare == null ? null : earningsPerShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.sales_margin
     *
     * @return the value of t_team_annual_worth_gather.sales_margin
     *
     * @mbggenerated
     */
    public String getSalesMargin() {
        return salesMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.sales_margin
     *
     * @param salesMargin the value for t_team_annual_worth_gather.sales_margin
     *
     * @mbggenerated
     */
    public void setSalesMargin(String salesMargin) {
        this.salesMargin = salesMargin == null ? null : salesMargin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.gross_margin
     *
     * @return the value of t_team_annual_worth_gather.gross_margin
     *
     * @mbggenerated
     */
    public String getGrossMargin() {
        return grossMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.gross_margin
     *
     * @param grossMargin the value for t_team_annual_worth_gather.gross_margin
     *
     * @mbggenerated
     */
    public void setGrossMargin(String grossMargin) {
        this.grossMargin = grossMargin == null ? null : grossMargin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.net_profit_margin_on_sales
     *
     * @return the value of t_team_annual_worth_gather.net_profit_margin_on_sales
     *
     * @mbggenerated
     */
    public String getNetProfitMarginOnSales() {
        return netProfitMarginOnSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.net_profit_margin_on_sales
     *
     * @param netProfitMarginOnSales the value for t_team_annual_worth_gather.net_profit_margin_on_sales
     *
     * @mbggenerated
     */
    public void setNetProfitMarginOnSales(String netProfitMarginOnSales) {
        this.netProfitMarginOnSales = netProfitMarginOnSales == null ? null : netProfitMarginOnSales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.operating_profit_ratio
     *
     * @return the value of t_team_annual_worth_gather.operating_profit_ratio
     *
     * @mbggenerated
     */
    public String getOperatingProfitRatio() {
        return operatingProfitRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.operating_profit_ratio
     *
     * @param operatingProfitRatio the value for t_team_annual_worth_gather.operating_profit_ratio
     *
     * @mbggenerated
     */
    public void setOperatingProfitRatio(String operatingProfitRatio) {
        this.operatingProfitRatio = operatingProfitRatio == null ? null : operatingProfitRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.year_over_year_growth_in_earnings_per_share
     *
     * @return the value of t_team_annual_worth_gather.year_over_year_growth_in_earnings_per_share
     *
     * @mbggenerated
     */
    public String getYearOverYearGrowthInEarningsPerShare() {
        return yearOverYearGrowthInEarningsPerShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.year_over_year_growth_in_earnings_per_share
     *
     * @param yearOverYearGrowthInEarningsPerShare the value for t_team_annual_worth_gather.year_over_year_growth_in_earnings_per_share
     *
     * @mbggenerated
     */
    public void setYearOverYearGrowthInEarningsPerShare(String yearOverYearGrowthInEarningsPerShare) {
        this.yearOverYearGrowthInEarningsPerShare = yearOverYearGrowthInEarningsPerShare == null ? null : yearOverYearGrowthInEarningsPerShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.year_over_year_growth_rate_of_operating_income
     *
     * @return the value of t_team_annual_worth_gather.year_over_year_growth_rate_of_operating_income
     *
     * @mbggenerated
     */
    public String getYearOverYearGrowthRateOfOperatingIncome() {
        return yearOverYearGrowthRateOfOperatingIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.year_over_year_growth_rate_of_operating_income
     *
     * @param yearOverYearGrowthRateOfOperatingIncome the value for t_team_annual_worth_gather.year_over_year_growth_rate_of_operating_income
     *
     * @mbggenerated
     */
    public void setYearOverYearGrowthRateOfOperatingIncome(String yearOverYearGrowthRateOfOperatingIncome) {
        this.yearOverYearGrowthRateOfOperatingIncome = yearOverYearGrowthRateOfOperatingIncome == null ? null : yearOverYearGrowthRateOfOperatingIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.year_on_year_growth_rate_of_net_profit
     *
     * @return the value of t_team_annual_worth_gather.year_on_year_growth_rate_of_net_profit
     *
     * @mbggenerated
     */
    public String getYearOnYearGrowthRateOfNetProfit() {
        return yearOnYearGrowthRateOfNetProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.year_on_year_growth_rate_of_net_profit
     *
     * @param yearOnYearGrowthRateOfNetProfit the value for t_team_annual_worth_gather.year_on_year_growth_rate_of_net_profit
     *
     * @mbggenerated
     */
    public void setYearOnYearGrowthRateOfNetProfit(String yearOnYearGrowthRateOfNetProfit) {
        this.yearOnYearGrowthRateOfNetProfit = yearOnYearGrowthRateOfNetProfit == null ? null : yearOnYearGrowthRateOfNetProfit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.year_over_year_return_on_equity_growth
     *
     * @return the value of t_team_annual_worth_gather.year_over_year_return_on_equity_growth
     *
     * @mbggenerated
     */
    public String getYearOverYearReturnOnEquityGrowth() {
        return yearOverYearReturnOnEquityGrowth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.year_over_year_return_on_equity_growth
     *
     * @param yearOverYearReturnOnEquityGrowth the value for t_team_annual_worth_gather.year_over_year_return_on_equity_growth
     *
     * @mbggenerated
     */
    public void setYearOverYearReturnOnEquityGrowth(String yearOverYearReturnOnEquityGrowth) {
        this.yearOverYearReturnOnEquityGrowth = yearOverYearReturnOnEquityGrowth == null ? null : yearOverYearReturnOnEquityGrowth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.rate_of_stock_turnover
     *
     * @return the value of t_team_annual_worth_gather.rate_of_stock_turnover
     *
     * @mbggenerated
     */
    public String getRateOfStockTurnover() {
        return rateOfStockTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.rate_of_stock_turnover
     *
     * @param rateOfStockTurnover the value for t_team_annual_worth_gather.rate_of_stock_turnover
     *
     * @mbggenerated
     */
    public void setRateOfStockTurnover(String rateOfStockTurnover) {
        this.rateOfStockTurnover = rateOfStockTurnover == null ? null : rateOfStockTurnover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.turnover_of_total_capital
     *
     * @return the value of t_team_annual_worth_gather.turnover_of_total_capital
     *
     * @mbggenerated
     */
    public String getTurnoverOfTotalCapital() {
        return turnoverOfTotalCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.turnover_of_total_capital
     *
     * @param turnoverOfTotalCapital the value for t_team_annual_worth_gather.turnover_of_total_capital
     *
     * @mbggenerated
     */
    public void setTurnoverOfTotalCapital(String turnoverOfTotalCapital) {
        this.turnoverOfTotalCapital = turnoverOfTotalCapital == null ? null : turnoverOfTotalCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.total_assets
     *
     * @return the value of t_team_annual_worth_gather.total_assets
     *
     * @mbggenerated
     */
    public String getTotalAssets() {
        return totalAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.total_assets
     *
     * @param totalAssets the value for t_team_annual_worth_gather.total_assets
     *
     * @mbggenerated
     */
    public void setTotalAssets(String totalAssets) {
        this.totalAssets = totalAssets == null ? null : totalAssets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.net_asset
     *
     * @return the value of t_team_annual_worth_gather.net_asset
     *
     * @mbggenerated
     */
    public String getNetAsset() {
        return netAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.net_asset
     *
     * @param netAsset the value for t_team_annual_worth_gather.net_asset
     *
     * @mbggenerated
     */
    public void setNetAsset(String netAsset) {
        this.netAsset = netAsset == null ? null : netAsset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.asset_liability_ratio
     *
     * @return the value of t_team_annual_worth_gather.asset_liability_ratio
     *
     * @mbggenerated
     */
    public String getAssetLiabilityRatio() {
        return assetLiabilityRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.asset_liability_ratio
     *
     * @param assetLiabilityRatio the value for t_team_annual_worth_gather.asset_liability_ratio
     *
     * @mbggenerated
     */
    public void setAssetLiabilityRatio(String assetLiabilityRatio) {
        this.assetLiabilityRatio = assetLiabilityRatio == null ? null : assetLiabilityRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.liquidity_ratio
     *
     * @return the value of t_team_annual_worth_gather.liquidity_ratio
     *
     * @mbggenerated
     */
    public String getLiquidityRatio() {
        return liquidityRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.liquidity_ratio
     *
     * @param liquidityRatio the value for t_team_annual_worth_gather.liquidity_ratio
     *
     * @mbggenerated
     */
    public void setLiquidityRatio(String liquidityRatio) {
        this.liquidityRatio = liquidityRatio == null ? null : liquidityRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.quick_ratio
     *
     * @return the value of t_team_annual_worth_gather.quick_ratio
     *
     * @mbggenerated
     */
    public String getQuickRatio() {
        return quickRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.quick_ratio
     *
     * @param quickRatio the value for t_team_annual_worth_gather.quick_ratio
     *
     * @mbggenerated
     */
    public void setQuickRatio(String quickRatio) {
        this.quickRatio = quickRatio == null ? null : quickRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.sales_growth_rate
     *
     * @return the value of t_team_annual_worth_gather.sales_growth_rate
     *
     * @mbggenerated
     */
    public String getSalesGrowthRate() {
        return salesGrowthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.sales_growth_rate
     *
     * @param salesGrowthRate the value for t_team_annual_worth_gather.sales_growth_rate
     *
     * @mbggenerated
     */
    public void setSalesGrowthRate(String salesGrowthRate) {
        this.salesGrowthRate = salesGrowthRate == null ? null : salesGrowthRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_operating_income_limousine
     *
     * @return the value of t_team_annual_worth_gather.composition_of_operating_income_limousine
     *
     * @mbggenerated
     */
    public String getCompositionOfOperatingIncomeLimousine() {
        return compositionOfOperatingIncomeLimousine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_operating_income_limousine
     *
     * @param compositionOfOperatingIncomeLimousine the value for t_team_annual_worth_gather.composition_of_operating_income_limousine
     *
     * @mbggenerated
     */
    public void setCompositionOfOperatingIncomeLimousine(String compositionOfOperatingIncomeLimousine) {
        this.compositionOfOperatingIncomeLimousine = compositionOfOperatingIncomeLimousine == null ? null : compositionOfOperatingIncomeLimousine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_operating_income_h6
     *
     * @return the value of t_team_annual_worth_gather.composition_of_operating_income_h6
     *
     * @mbggenerated
     */
    public String getCompositionOfOperatingIncomeH6() {
        return compositionOfOperatingIncomeH6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_operating_income_h6
     *
     * @param compositionOfOperatingIncomeH6 the value for t_team_annual_worth_gather.composition_of_operating_income_h6
     *
     * @mbggenerated
     */
    public void setCompositionOfOperatingIncomeH6(String compositionOfOperatingIncomeH6) {
        this.compositionOfOperatingIncomeH6 = compositionOfOperatingIncomeH6 == null ? null : compositionOfOperatingIncomeH6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_operating_income_pickup
     *
     * @return the value of t_team_annual_worth_gather.composition_of_operating_income_pickup
     *
     * @mbggenerated
     */
    public String getCompositionOfOperatingIncomePickup() {
        return compositionOfOperatingIncomePickup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_operating_income_pickup
     *
     * @param compositionOfOperatingIncomePickup the value for t_team_annual_worth_gather.composition_of_operating_income_pickup
     *
     * @mbggenerated
     */
    public void setCompositionOfOperatingIncomePickup(String compositionOfOperatingIncomePickup) {
        this.compositionOfOperatingIncomePickup = compositionOfOperatingIncomePickup == null ? null : compositionOfOperatingIncomePickup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_operating_income_wey
     *
     * @return the value of t_team_annual_worth_gather.composition_of_operating_income_wey
     *
     * @mbggenerated
     */
    public String getCompositionOfOperatingIncomeWey() {
        return compositionOfOperatingIncomeWey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_operating_income_wey
     *
     * @param compositionOfOperatingIncomeWey the value for t_team_annual_worth_gather.composition_of_operating_income_wey
     *
     * @mbggenerated
     */
    public void setCompositionOfOperatingIncomeWey(String compositionOfOperatingIncomeWey) {
        this.compositionOfOperatingIncomeWey = compositionOfOperatingIncomeWey == null ? null : compositionOfOperatingIncomeWey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_operating_income_h8
     *
     * @return the value of t_team_annual_worth_gather.composition_of_operating_income_h8
     *
     * @mbggenerated
     */
    public String getCompositionOfOperatingIncomeH8() {
        return compositionOfOperatingIncomeH8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_operating_income_h8
     *
     * @param compositionOfOperatingIncomeH8 the value for t_team_annual_worth_gather.composition_of_operating_income_h8
     *
     * @mbggenerated
     */
    public void setCompositionOfOperatingIncomeH8(String compositionOfOperatingIncomeH8) {
        this.compositionOfOperatingIncomeH8 = compositionOfOperatingIncomeH8 == null ? null : compositionOfOperatingIncomeH8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_net_profit_limousine
     *
     * @return the value of t_team_annual_worth_gather.composition_of_net_profit_limousine
     *
     * @mbggenerated
     */
    public String getCompositionOfNetProfitLimousine() {
        return compositionOfNetProfitLimousine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_net_profit_limousine
     *
     * @param compositionOfNetProfitLimousine the value for t_team_annual_worth_gather.composition_of_net_profit_limousine
     *
     * @mbggenerated
     */
    public void setCompositionOfNetProfitLimousine(String compositionOfNetProfitLimousine) {
        this.compositionOfNetProfitLimousine = compositionOfNetProfitLimousine == null ? null : compositionOfNetProfitLimousine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_net_profit_h6
     *
     * @return the value of t_team_annual_worth_gather.composition_of_net_profit_h6
     *
     * @mbggenerated
     */
    public String getCompositionOfNetProfitH6() {
        return compositionOfNetProfitH6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_net_profit_h6
     *
     * @param compositionOfNetProfitH6 the value for t_team_annual_worth_gather.composition_of_net_profit_h6
     *
     * @mbggenerated
     */
    public void setCompositionOfNetProfitH6(String compositionOfNetProfitH6) {
        this.compositionOfNetProfitH6 = compositionOfNetProfitH6 == null ? null : compositionOfNetProfitH6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_net_profit_pickup
     *
     * @return the value of t_team_annual_worth_gather.composition_of_net_profit_pickup
     *
     * @mbggenerated
     */
    public String getCompositionOfNetProfitPickup() {
        return compositionOfNetProfitPickup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_net_profit_pickup
     *
     * @param compositionOfNetProfitPickup the value for t_team_annual_worth_gather.composition_of_net_profit_pickup
     *
     * @mbggenerated
     */
    public void setCompositionOfNetProfitPickup(String compositionOfNetProfitPickup) {
        this.compositionOfNetProfitPickup = compositionOfNetProfitPickup == null ? null : compositionOfNetProfitPickup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_net_profit_wey
     *
     * @return the value of t_team_annual_worth_gather.composition_of_net_profit_wey
     *
     * @mbggenerated
     */
    public String getCompositionOfNetProfitWey() {
        return compositionOfNetProfitWey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_net_profit_wey
     *
     * @param compositionOfNetProfitWey the value for t_team_annual_worth_gather.composition_of_net_profit_wey
     *
     * @mbggenerated
     */
    public void setCompositionOfNetProfitWey(String compositionOfNetProfitWey) {
        this.compositionOfNetProfitWey = compositionOfNetProfitWey == null ? null : compositionOfNetProfitWey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.composition_of_net_profit_h8
     *
     * @return the value of t_team_annual_worth_gather.composition_of_net_profit_h8
     *
     * @mbggenerated
     */
    public String getCompositionOfNetProfitH8() {
        return compositionOfNetProfitH8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.composition_of_net_profit_h8
     *
     * @param compositionOfNetProfitH8 the value for t_team_annual_worth_gather.composition_of_net_profit_h8
     *
     * @mbggenerated
     */
    public void setCompositionOfNetProfitH8(String compositionOfNetProfitH8) {
        this.compositionOfNetProfitH8 = compositionOfNetProfitH8 == null ? null : compositionOfNetProfitH8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.development_expenditure
     *
     * @return the value of t_team_annual_worth_gather.development_expenditure
     *
     * @mbggenerated
     */
    public String getDevelopmentExpenditure() {
        return developmentExpenditure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.development_expenditure
     *
     * @param developmentExpenditure the value for t_team_annual_worth_gather.development_expenditure
     *
     * @mbggenerated
     */
    public void setDevelopmentExpenditure(String developmentExpenditure) {
        this.developmentExpenditure = developmentExpenditure == null ? null : developmentExpenditure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.development_expenditure_percentage_revenue
     *
     * @return the value of t_team_annual_worth_gather.development_expenditure_percentage_revenue
     *
     * @mbggenerated
     */
    public String getDevelopmentExpenditurePercentageRevenue() {
        return developmentExpenditurePercentageRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.development_expenditure_percentage_revenue
     *
     * @param developmentExpenditurePercentageRevenue the value for t_team_annual_worth_gather.development_expenditure_percentage_revenue
     *
     * @mbggenerated
     */
    public void setDevelopmentExpenditurePercentageRevenue(String developmentExpenditurePercentageRevenue) {
        this.developmentExpenditurePercentageRevenue = developmentExpenditurePercentageRevenue == null ? null : developmentExpenditurePercentageRevenue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.h6_market_share
     *
     * @return the value of t_team_annual_worth_gather.h6_market_share
     *
     * @mbggenerated
     */
    public String getH6MarketShare() {
        return h6MarketShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.h6_market_share
     *
     * @param h6MarketShare the value for t_team_annual_worth_gather.h6_market_share
     *
     * @mbggenerated
     */
    public void setH6MarketShare(String h6MarketShare) {
        this.h6MarketShare = h6MarketShare == null ? null : h6MarketShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.h8_market_share
     *
     * @return the value of t_team_annual_worth_gather.h8_market_share
     *
     * @mbggenerated
     */
    public String getH8MarketShare() {
        return h8MarketShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.h8_market_share
     *
     * @param h8MarketShare the value for t_team_annual_worth_gather.h8_market_share
     *
     * @mbggenerated
     */
    public void setH8MarketShare(String h8MarketShare) {
        this.h8MarketShare = h8MarketShare == null ? null : h8MarketShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.wey_market_share
     *
     * @return the value of t_team_annual_worth_gather.wey_market_share
     *
     * @mbggenerated
     */
    public String getWeyMarketShare() {
        return weyMarketShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.wey_market_share
     *
     * @param weyMarketShare the value for t_team_annual_worth_gather.wey_market_share
     *
     * @mbggenerated
     */
    public void setWeyMarketShare(String weyMarketShare) {
        this.weyMarketShare = weyMarketShare == null ? null : weyMarketShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.new_product_contribution_rate
     *
     * @return the value of t_team_annual_worth_gather.new_product_contribution_rate
     *
     * @mbggenerated
     */
    public String getNewProductContributionRate() {
        return newProductContributionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.new_product_contribution_rate
     *
     * @param newProductContributionRate the value for t_team_annual_worth_gather.new_product_contribution_rate
     *
     * @mbggenerated
     */
    public void setNewProductContributionRate(String newProductContributionRate) {
        this.newProductContributionRate = newProductContributionRate == null ? null : newProductContributionRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.class_id
     *
     * @return the value of t_team_annual_worth_gather.class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.class_id
     *
     * @param classId the value for t_team_annual_worth_gather.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_annual_worth_gather.team_id
     *
     * @return the value of t_team_annual_worth_gather.team_id
     *
     * @mbggenerated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_annual_worth_gather.team_id
     *
     * @param teamId the value for t_team_annual_worth_gather.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_annual_worth_gather
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", year=").append(year);
        sb.append(", netAssetsIncomeRate=").append(netAssetsIncomeRate);
        sb.append(", retainedProfits=").append(retainedProfits);
        sb.append(", operationRevenue=").append(operationRevenue);
        sb.append(", netAssetValuePerShare=").append(netAssetValuePerShare);
        sb.append(", earningsPerShare=").append(earningsPerShare);
        sb.append(", salesMargin=").append(salesMargin);
        sb.append(", grossMargin=").append(grossMargin);
        sb.append(", netProfitMarginOnSales=").append(netProfitMarginOnSales);
        sb.append(", operatingProfitRatio=").append(operatingProfitRatio);
        sb.append(", yearOverYearGrowthInEarningsPerShare=").append(yearOverYearGrowthInEarningsPerShare);
        sb.append(", yearOverYearGrowthRateOfOperatingIncome=").append(yearOverYearGrowthRateOfOperatingIncome);
        sb.append(", yearOnYearGrowthRateOfNetProfit=").append(yearOnYearGrowthRateOfNetProfit);
        sb.append(", yearOverYearReturnOnEquityGrowth=").append(yearOverYearReturnOnEquityGrowth);
        sb.append(", rateOfStockTurnover=").append(rateOfStockTurnover);
        sb.append(", turnoverOfTotalCapital=").append(turnoverOfTotalCapital);
        sb.append(", totalAssets=").append(totalAssets);
        sb.append(", netAsset=").append(netAsset);
        sb.append(", assetLiabilityRatio=").append(assetLiabilityRatio);
        sb.append(", liquidityRatio=").append(liquidityRatio);
        sb.append(", quickRatio=").append(quickRatio);
        sb.append(", salesGrowthRate=").append(salesGrowthRate);
        sb.append(", compositionOfOperatingIncomeLimousine=").append(compositionOfOperatingIncomeLimousine);
        sb.append(", compositionOfOperatingIncomeH6=").append(compositionOfOperatingIncomeH6);
        sb.append(", compositionOfOperatingIncomePickup=").append(compositionOfOperatingIncomePickup);
        sb.append(", compositionOfOperatingIncomeWey=").append(compositionOfOperatingIncomeWey);
        sb.append(", compositionOfOperatingIncomeH8=").append(compositionOfOperatingIncomeH8);
        sb.append(", compositionOfNetProfitLimousine=").append(compositionOfNetProfitLimousine);
        sb.append(", compositionOfNetProfitH6=").append(compositionOfNetProfitH6);
        sb.append(", compositionOfNetProfitPickup=").append(compositionOfNetProfitPickup);
        sb.append(", compositionOfNetProfitWey=").append(compositionOfNetProfitWey);
        sb.append(", compositionOfNetProfitH8=").append(compositionOfNetProfitH8);
        sb.append(", developmentExpenditure=").append(developmentExpenditure);
        sb.append(", developmentExpenditurePercentageRevenue=").append(developmentExpenditurePercentageRevenue);
        sb.append(", h6MarketShare=").append(h6MarketShare);
        sb.append(", h8MarketShare=").append(h8MarketShare);
        sb.append(", weyMarketShare=").append(weyMarketShare);
        sb.append(", newProductContributionRate=").append(newProductContributionRate);
        sb.append(", classId=").append(classId);
        sb.append(", teamId=").append(teamId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}